#!/bin/sh

CUR_DIR=`dirname $0`
CUR_DIR=`pwd $CUR_DIR`
cd $CUR_DIR

ORIG_NAME="orbited-0.7.11beta3/"
NAME="python26-orbited"
RELEASE="beta3"
PACKAGER="Nick Bailey - nick@riptano.com"
DOC_FILES="PKG-INFO, LICENSE"
REQUIRES=""
BUILD_REQUIRES=""

# copy to a directory for building
cp -r $ORIG_NAME $NAME/
#apply any patches
for patch_file in patches/*
do
    patch -p1 -d $NAME < $patch_file
done

# build rpms
cd $NAME
python2.6 setup.py bdist_rpm \
        --python="python2.6" \
        --dist-dir="$CUR_DIR" \
        --release="$RELEASE" \
        --packager="$PACKAGER" \
        --doc-files="$DOC_FILES"
cd ..

rm -r "$CUR_DIR/$NAME"

